/*
==========================================================================
This file is part of PNG2WAD, a tool to create Doom maps from PNG files,
created by @akaAgar (https://github.com/akaAgar/png2wad)

PNG2WAD is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

PNG2WAD is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with PNG2WAD. If not, see https://www.gnu.org/licenses/
==========================================================================
*/

using PNG2WAD.Config;
using PNG2WAD.Doom.Map;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;

namespace PNG2WAD.Generator
{
    /// <summary>
    /// Things generator. Creates player starts, items, monsters and other things.
    /// </summary>
    public sealed class ThingsGenerator : IDisposable
    {
        /// <summary>
        /// Default angle is North.
        /// </summary>
        private const int DEFAULT_ANGLE = 90;

        /// <summary>
        /// Number of deathmatch starts.
        /// </summary>
        private const int DEATHMATCH_STARTS_COUNT = 8;

        /// <summary>
        /// PNG2WAD Preferences.
        /// </summary>
        private readonly Preferences Preferences;
        
        /// <summary>
        /// List of 64x64 where a thing can be spawned.
        /// </summary>
        private readonly List<Point> FreeTiles;

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="preferences">PNG2WAD preferences</param>
        public ThingsGenerator(Preferences preferences)
        {
            Preferences = preferences;

            FreeTiles = new List<Point>();
        }

        /// <summary>
        /// Create all required things on a map.
        /// </summary>
        /// <param name="map">The Doom map on which to create things</param>
        /// <param name="subTiles">Map sub-tiles generated by MapGenerator</param>
        public void CreateThings(DoomMap map, TileType[,] subTiles)
        {
            int i, x, y;

            FreeTiles.Clear();
            for (x = 0; x < subTiles.GetLength(0); x += MapGenerator.SUBTILE_DIVISIONS)
                for (y = 0; y < subTiles.GetLength(1); y += MapGenerator.SUBTILE_DIVISIONS)
                {
                    switch (subTiles[x,y])
                    {
                        case TileType.Door:
                        case TileType.DoorSide:
                        case TileType.Entrance:
                        case TileType.Exit:
                        case TileType.Secret:
                        case TileType.Wall:
                            continue;
                    }

                    FreeTiles.Add(new Point(x / MapGenerator.SUBTILE_DIVISIONS, y / MapGenerator.SUBTILE_DIVISIONS));
                }


            if (Preferences.GenerateEntranceAndExit)
            { 
                AddPlayerStarts(map, subTiles); // Single-player and coop starts (spawned on entrances, or next to each other is none found)
                AddThings(map, DEATHMATCH_STARTS_COUNT, 0, 11); // Deathmatch starts (spawned anywhere on the map)
            }

            float thingsCountMultiplier = FreeTiles.Count / 1000.0f; // Bigger map = more things

            if (Preferences.GenerateThings)
            {
                for (i = 0; i < Preferences.THINGS_CATEGORY_COUNT; i++)
                    AddThings(map, (ThingCategory)i,
                        (int)(Preferences.ThingsCount[i][0] * thingsCountMultiplier),
                        (int)(Preferences.ThingsCount[i][1] * thingsCountMultiplier));
            }
        }

        /// <summary>
        /// Adds a random number of things from a certain ThingCategory.
        /// </summary>
        /// <param name="map">The Doom map on which to add things</param>
        /// <param name="thingCategory">The thing category from which to pick thing types</param>
        /// <param name="minCount">Min number of things to add</param>
        /// <param name="maxCount">Max number of things to add</param>
        /// <param name="generationFlags">Special flags for thing generation</param>
        private void AddThings(DoomMap map, ThingCategory thingCategory, int minCount, int maxCount, ThingsGeneratorFlags generationFlags = 0)
        {
            int count = Toolbox.RandomInt(minCount, maxCount + 1);
            AddThings(map, count, generationFlags, Preferences.ThingsTypes[(int)thingCategory]);
        }

        /// <summary>
        /// Add a certain number of things from an array of thing types to a map.
        /// </summary>
        /// <param name="map">The Doom map on which to add things</param>
        /// <param name="count">The number of things to add</param>
        /// <param name="generationFlags">Special flags for thing generation</param>
        /// <param name="thingTypes">Array of thing types to select from</param>
        private void AddThings(DoomMap map, int count, ThingsGeneratorFlags generationFlags, params int[] thingTypes)
        {
            if ((count < 1) || (thingTypes.Length == 0)) return;

            for (int i = 0; i < count; i++)
            {
                if (FreeTiles.Count == 0) return;

                ThingOptions options = ThingOptions.AllSkills;

                switch (generationFlags)
                {
                    case ThingsGeneratorFlags.MoreThingsInEasyMode:
                        if (Toolbox.RandomInt(4) == 0) options = ThingOptions.Skill12 | ThingOptions.Skill3;
                        else if (Toolbox.RandomInt(3) == 0) options = ThingOptions.Skill12;
                        break;
                    case ThingsGeneratorFlags.MoreThingsInHardMode:
                        if (Toolbox.RandomInt(3) == 0) options = ThingOptions.Skill3 | ThingOptions.Skill45;
                        else if (Toolbox.RandomInt(2) == 0) options = ThingOptions.Skill45;
                        break;
                }

                int thingType = Toolbox.RandomFromArray(thingTypes);
                Point pt = Toolbox.RandomFromList(FreeTiles);
                AddThing(map, pt.X, pt.Y, thingType, Toolbox.RandomInt(360), options);
                FreeTiles.Remove(pt);
            }
        }

        /// <summary>
        /// Adds player starts to the map
        /// </summary>
        /// <param name="map">Doom map to add player starts to</param>
        /// <param name="subTiles">Map sub-tiles generated by MapGenerator</param>
        private void AddPlayerStarts(DoomMap map, TileType[,] subTiles)
        {
            int x, y;
            List<Point> entrances = new();

            // Spawn a single-player/coop entrance for each of the four players
            for (int player = 1; player <= 4; player++)
            {
                bool foundAnEntrance = false;

                // First try to look for a free "entrance" tile
                for (x = 0; x < subTiles.GetLength(0); x+= MapGenerator.SUBTILE_DIVISIONS)
                    for (y = 0; y < subTiles.GetLength(1); y += MapGenerator.SUBTILE_DIVISIONS)
                    {
                        if (!foundAnEntrance && (subTiles[x, y] == TileType.Entrance))
                        {
                            Point entranceTile = new(x / MapGenerator.SUBTILE_DIVISIONS, y / MapGenerator.SUBTILE_DIVISIONS);
                            if (entrances.Contains(entranceTile)) continue; // Entrance already in use
                            AddThing(map, x / MapGenerator.SUBTILE_DIVISIONS, y / MapGenerator.SUBTILE_DIVISIONS, player);
                            entrances.Add(entranceTile);
                            foundAnEntrance = true;
                        }
                    }

                if (foundAnEntrance) continue;

                // No "entrance" tile found for this player, so...
                if (FreeTiles.Count > 0)
                {
                    Point tile;

                    // ...if no player entrance has been selected yet, spawn the player on a random free tile
                    if (entrances.Count == 0)
                        tile = Toolbox.RandomFromList(FreeTiles);
                    // ...else spawn the player on the nearest free tile from player 1 start
                    else
                        tile = (from Point t in FreeTiles select t).OrderBy(t => t.Distance(entrances[0])).First();

                    FreeTiles.Remove(tile);
                    AddThing(map, tile.X, tile.Y, player);
                    entrances.Add(tile);
                    foundAnEntrance = true;
                }

                if (foundAnEntrance) continue;

                // No free spot, put the player start in the northwest map corner.
                // Should never happen unless the map is entirely made of walls, doors or other unpassable stuff.
                // Might be outside a sector but at least the map won't crash with a "no player start found" error.
                AddThing(map, player - 1, 0, player);
                entrances.Add(new Point(player - 1, 0));
            }
        }

        /// <summary>
        /// Adds a thing to the map.
        /// </summary>
        /// <param name="map">Doom map the thing should be added to</param>
        /// <param name="x">X coordinate of the tile on which the thing should be spawned</param>
        /// <param name="y">Y coordinate of the tile on which the thing should be spanwed</param>
        /// <param name="thingType">Type of thing</param>
        /// <param name="angle">Angle the thing should face</param>
        /// <param name="options">Thing options</param>
        private static void AddThing(DoomMap map, int x, int y, int thingType, int angle = (int)DEFAULT_ANGLE, ThingOptions options = ThingOptions.AllSkills)
        {
            map.Things.Add(
                new Thing(
                    (int)((x + .5f) * MapGenerator.TILE_SIZE),
                    (int)((y + .5f) * -MapGenerator.TILE_SIZE),
                    thingType, angle, options));
        }

        /// <summary>
        /// IDisposable implementation.
        /// </summary>
        public void Dispose() { }
    }
}
 